server:
  port: 8762

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,refresh
health:
  config:
    enabled: false
spring:
  application:
    name: eureka-server
  config:
    import:
      - optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: eureka-server  