server:
  port: 9000
eureka:
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000 
spring:
  cloud:
    gateway:    
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: diet-service
          uri: lb://DIET-SERVICE
          predicates:
            - Path=/diets/**
        - id: diet-service
          uri: lb://DIET-SERVICE
          predicates:
            - Path=/translate/**
        - id: diets-groups-service
          uri: lb://DIETS-GROUPS-SERVICE
          predicates:
            - Path=/diets-groups/**
        - id: nutritionist-service
          uri: lb://NUTRITIONIST-SERVICE
          predicates:
            - Path=/nutritionist/**
        - id: patient-service
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patient/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,refresh