server:
  port: 9000
eureka:
  instance:
    hostname: localhost
    port: 8762
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000   
spring:
  jackson:
    default-property-inclusion: NON_NULL    
  cloud:
    gateway:    
      discovery:
        locator:
          enabled: true
      routes:
        - id: diet-service
          uri: lb://DIET-SERVICE
          predicates:
            - Path=/diet-service/**
        - id: diets-groups-service
          uri: lb://DIETS-GROUPS-SERVICE
          predicates:
            - Path=/diets-groups-service/**
        - id: nutritionist-service
          uri: lb://NUTRITIONIST-SERVICE
          predicates:
            - Path=/nutritionist-service/**
        - id: patient-service
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patient-service/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**
        - id: openapi
          uri: lb://GATEWAY
          predicates:
          - Path=/v3/api-docs/**
          filters:
          - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,refresh
jwt:
  secret: secretkey
  token:
    validity: 180000